name: build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # At 00:00 on Monday
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=github-releases depName=jsonnet-bundler/jsonnet-bundler
  JB_VERSION: v0.5.1
  # renovate: datasource=github-releases depName=google/go-jsonnet
  JSONNET_VERSION: v0.20.0

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 60

    defaults:
      run:
        working-directory: examples

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Jsonnet
        run: |
          mkdir -p "${HOME}/.local/bin"
          echo "${HOME}/.local/bin" >>"${GITHUB_PATH}"
          gh --repo=google/go-jsonnet release download "${JSONNET_VERSION}" \
            --output=- --pattern='go-jsonnet_*_Linux_x86_64.tar.gz' \
            | tar -zxvf - -C "${HOME}/.local/bin" jsonnet jsonnet-lint jsonnetfmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Jsonnet Bundler
        run: |
          gh --repo=jsonnet-bundler/jsonnet-bundler release download "${JB_VERSION}" \
            --output="${HOME}/.local/bin/jb" --pattern=jb-linux-amd64
          chmod +x "${HOME}/.local/bin/jb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint examples
        run: make lint

      - name: Build examples
        run: make
